### ISSUE TITLE
Allow zooming using the numpad +/- keys

### ISSUE THREAD

**Issue by SpitFire-666** [TheFantasticWarrior/chrome-extension-imagus#15]
Hey small thing I noticed that I used to use in the OG Imagus.

When hitting ```z``` to turn on Zoom mode, the +/- keys on the numpad don't work, but the ones on the number row do.

Hoping this behaviour can be restored 🙏

Thanks!

**Comment by kuzn123** [comment]
I just wanted to clarify: why use +/- when there is a mouse wheel (MMB)? In my opinion, MMB scaling is much more convenient.

**Comment by SpitFire-666** [comment]
Fair question - since I'm on a laptop I prefer using keys instead of touchpad wherever possible. This is coz the keys are more precise. Cheers!

**Comment by TheFantasticWarrior** [comment]
One question, would you want +/- treated as the ones in number row or separately?
If you only want the +/- on numpad but not the number row you can assign it to +/- on numpad, which is named Add and Subtract instead of Equal and Minus.
If you want both to work at the same time, I'll have to rename it to Equal(Add) to avoid confusion, but all users will have to reassign their keys after update unless I figure out a way to avoid that.

**Comment by SpitFire-666** [comment]
Hey just tested OG Imagus and both types of +/- keys work. 

I think it would be a good idea to implement both - although personally I mostly use the numpad (as my laptop has one) but I could be in the minority on that. Cheers

**Comment by TheFantasticWarrior** [comment]
not sure if it's a good idea but added in v0.10.10.1
