### ISSUE TITLE
v0.10.11.1 Doesn't work on sites where cookies are needed.

### ISSUE THREAD

**Issue by 54m4d** [TheFantasticWarrior/chrome-extension-imagus#21]
Hi

As the titles says, `v0.10.11.1` is not allowing sites where one is logged in like Instagram and YouTube etc.., to work, because it inroduced a cookie bug.

I think it's related to the cookies not being allowed or something related.

I reverted to the previous version and i can confirm that the issue does not exist and imagus works as expected.

**Comment by TheFantasticWarrior** [comment]
Unfortunately I tested youtube and in console it appears the error 
`Imagus mod: [rule 534] (new RegExp(...)).exec(...) is null`
no matter the version(v0.10.10.1, v0.10.11, v0.10.11.1, old imagus) or sieve version(newest and old one I had for a while, the error number changes but message stays the same)
and **I have no idea what's going on** because before uploading I did test youtube
maybe youtube changed something so it doesn't work but that doesn't make sense if it still works for you in old version

as for instagram sorry but I dont have an account

**Comment by 54m4d** [comment]
Even if you have a working rule, it would not work unless you use v0.10.11, and the issue is not only YT and IG but almost all the sites wherelogin is required.

Check reddit, i think there is a working sieve for youtube and you can use it to test.

**Comment by TheFantasticWarrior** [comment]
> Check reddit, i think there is a working sieve for youtube and you can use it to test.

Thank you for letting me know

Should be fixed, I uploaded under the same version number. https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/download/v0.10.11.1/imagus_mod-0.10.11.1.zip

**Comment by 54m4d** [comment]
But what caused the issue with the latest release?

**Comment by 54m4d** [comment]
But what caused the issue with the latest release? also, i'm not sure what's new in `v0.10.11.1`

**Comment by TheFantasticWarrior** [comment]
I moved the xhr call to content script instead of background script as said in https://bugzilla.mozilla.org/show_bug.cgi?id=1833842 to fix the bug mentioned. To achieve that I had to pass things back and forth, and didn't remove the previous listener when adding an extra one. Can you confirm that the sites you tested are working now?

**Comment by 54m4d** [comment]
Okay, I use Chrome, and I haven't personally encountered cookies being saved in private mode. However, I believe cookies are typically saved temporarily until you close the session in order for websites to function properly.

Yes, the bug fix is working now. Thanks.

**Comment by kuzn123** [comment]
On the new version 0.10.11.1 (from 25-06-2023) there were problems with **R_Fastpic** (the largest hosting in Russia and one of the largest in the world) and most likely there may be problems with other sieves.

You can check here (screenshots):
https://rutracker.org/forum/viewtopic.php?t=6087782
https://rutracker.org/forum/viewtopic.php?t=6379083
https://rutracker.org/forum/viewtopic.php?t=6379131
https://rutracker.org/forum/viewtopic.php?t=6379155

There are no problems with **R_Fastpic** on version 0.10.11. Tested on two browsers: Cent (Chromium 102) and Opera 100 (Chromium 114).

**Comment by Max33Verstappen** [comment]
This version (0.10.11.1) may have a problem. (Tested on Chrome)
With it, I can no longer preview YT cover image in [inoreader.com](https://www.inoreader.com). (Using a simple sieve and disabling all other YT sieves)
![2023-06-27_22 32 18 583_chrome_Inoreader_-_carwow_-_httpswww inoreader comfeedhtt](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/97274607/6e6c5f91-4c46-4b7a-8a17-c7a15a85838d)

Have no problem using 0.10.11.
![2023-06-27_22 43 14 350_chrome_Inoreader_-_carwow_-_httpswww inoreader comfeedhtt](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/97274607/378823c0-a295-4af3-aee5-e5e7f07c35ec)



[Imagus mod-sieve__youtube.zip](https://github.com/TheFantasticWarrior/chrome-extension-imagus/files/11883370/Imagus.mod-sieve__youtube.zip)

**Comment by TheFantasticWarrior** [comment]
> On the new version 0.10.11.1 (from 25-06-2023) there were problems with **R_Fastpic** (the largest hosting in Russia and one of the largest in the world) and most likely there may be problems with other sieves.
> 
> You can check here (screenshots): https://rutracker.org/forum/viewtopic.php?t=6087782 https://rutracker.org/forum/viewtopic.php?t=6379083 https://rutracker.org/forum/viewtopic.php?t=6379131 https://rutracker.org/forum/viewtopic.php?t=6379155
> 
> There are no problems with **R_Fastpic** on version 0.10.11. Tested on two browsers: Cent (Chromium 102) and Opera 100 (Chromium 114).

The images in blue circle works for me in new version, 
the image in red circle doesn't work for me even on 0.10.11, tested on firefox and ungoogled-chromium
![2023-06-30 10-44-02](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/39485135/7f76719f-1cef-4039-ac39-e06905282f89)



> This version (0.10.11.1) may have a problem. (Tested on Chrome) With it, I can no longer preview YT cover image in [inoreader.com](https://www.inoreader.com). (Using a simple sieve and disabling all other YT sieves) ![2023-06-27_22 32 18 583_chrome_Inoreader_-carwow-_httpswww inoreader comfeedhtt](https://user-images.githubusercontent.com/97274607/249186681-6e6c5f91-4c46-4b7a-8a17-c7a15a85838d.png)
> 
> Have no problem using 0.10.11. ![2023-06-27_22 43 14 350_chrome_Inoreader_-carwow-_httpswww inoreader comfeedhtt](https://user-images.githubusercontent.com/97274607/249190562-378823c0-a295-4af3-aee5-e5e7f07c35ec.png)
> 
> [Imagus mod-sieve__youtube.zip](https://github.com/TheFantasticWarrior/chrome-extension-imagus/files/11883370/Imagus.mod-sieve__youtube.zip)

works fine directly on firefox, for chrome you need a simple-modify-headers rule Access-Control-Allow-Origin like so
![image](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/39485135/a170b8e4-aa45-4bf5-aac5-84b91d2d3ca2)

this is because I moved the call from background script to the page, which causes chrome to block cross site requests
without the change incognito is less safe on firefox, so in the future I might have to separate chrome and firefox versions if I don't find a workaround
I might add the ability to modify header directly in the imagus mod extension itself in the future, like [this project](https://github.com/sandsmark/chrome-extension-imagus/tree/martin/header-fixes)

**Comment by Max33Verstappen** [comment]
> works fine directly on firefox, for chrome you need a simple-modify-headers rule Access-Control-Allow-Origin like so ![image](https://user-images.githubusercontent.com/39485135/249983545-a170b8e4-aa45-4bf5-aac5-84b91d2d3ca2.png)
> 
> this is because I moved the call from background script to the page, which causes chrome to block cross site requests without the change incognito is less safe on firefox, so in the future I might have to separate chrome and firefox versions if I don't find a workaround I might add the ability to modify header directly in the imagus mod extension itself in the future, like [this project](https://github.com/sandsmark/chrome-extension-imagus/tree/martin/header-fixes)

OK.
Managed to make it work. But in my case, it must be `Add` instead of `Modify` to make it work, otherwise, it still complained about XHR violating CORS policy. Thanks
![2023-06-30_20 03 26 072_chrome_Simple_Modify_Headers_-_Google_Chrome](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/97274607/f1b76065-ec33-48e7-8a74-d4ad56c22497)

**Comment by TheFantasticWarrior** [comment]
> On the new version 0.10.11.1 (from 25-06-2023) there were problems with **R_Fastpic** (the largest hosting in Russia and one of the largest in the world) and most likely there may be problems with other sieves.
> 
> You can check here (screenshots): https://rutracker.org/forum/viewtopic.php?t=6087782 https://rutracker.org/forum/viewtopic.php?t=6379083 https://rutracker.org/forum/viewtopic.php?t=6379131 https://rutracker.org/forum/viewtopic.php?t=6379155
> 
> There are no problems with **R_Fastpic** on version 0.10.11. Tested on two browsers: Cent (Chromium 102) and Opera 100 (Chromium 114).

![image](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/39485135/8cc7eb52-a470-404f-bcc9-bc03f7f88608)
@kuzn123 does it work with those SMH settings?
