### ISSUE TITLE
Duplicate Import/Export options?

### ISSUE THREAD

**Issue by 54m4d** [TheFantasticWarrior/chrome-extension-imagus#24]
Hello

There is a duplicate of the import/export options in Chrome, i noticed they are the same, please try to delete one of the options.

I think you can delete the original option (red) and keep the mod option (blue) because the (blue) one can be accessed quickly and easily.

Thanks for your attention.

<details>
<summary>Screen</summary>
<img src=https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/52612348/dc0dd66b-4614-405f-86af-0b625fe05af3 alt="">
</details>

**Comment by TheFantasticWarrior** [comment]
There's a slight difference that in the original button the sieve isn't imported/exported, and I only added the new one because I didn't know the original existed
the original is more well coded, and not including the sieve will reduce the file size as it can be separately exported/just use the update button
I might move the original button to the right panel with the text kept, or leave it untouched in case someone might think one is more useful than the other

**Comment by 54m4d** [comment]
I checked it again, the only difference is one includes the sieves and one does not, maybe it's a good idea to replace the the new one with the original one since it's lighter and well integrated, but having 2 options is confusing in my opinion.
For the sieves we can just update them since they are always getting updated, so no need to export them.

**Comment by 54m4d** [comment]
Looks perfect now. Good.

**Comment by 54m4d** [comment]
1ec6bc6
