### ISSUE TITLE
Absolutely mind-boggled rn. By default when trying to save imgur image link from reddit, it will save html. Followed a tutorial to update sieves properly, now nothing is solved while Ctrl + S doesn't even save anything anymore. Wth am I supposed to do?!?

### ISSUE THREAD

**Issue by ReEnMikki** [TheFantasticWarrior/chrome-extension-imagus#58]
Sorry, it's just frustrating that wanting something so simple can be so annoyingly confusing. What am I missing here?

**Comment by ReEnMikki** [comment]
Btw I mean that it will still display zoomed image, but Ctrl + S now does absolutely nothing. Does someone have fixed sieve for imgur I can apply or something?

**Comment by ReEnMikki** [comment]
(Also btw it tries to save the html of the current reddit page with the imgur image hyperlink I'm pointing at)

**Comment by kuzn123** [comment]
I'm not sure if your problem is related to the Imagus Mod. Personally, I have no problems saving content from Imgur by pressing S (I have it assigned instead of Ctrl+S). Ask your question in the [Imagus Reddit](https://www.reddit.com/r/imagus/hot/) community.

**Comment by ReEnMikki** [comment]
> I'm not sure if your problem is related to the Imagus Mod. Personally, I have no problems saving content from Imgur by pressing S (I have it assigned instead of Ctrl+S). Ask your question in the [Imagus Reddit](https://www.reddit.com/r/imagus/hot/) community.

Some time ago I already issued this - The original supposedly "worse" Imagus on the Chrome extension store works fine. But this modded one, everything I try to save Ctrl + S, it tries to save the HTML instead of the actual image itself. I already deleted the original Imagus. Updating sieves makes the situation worse by causing the Ctrl + S to be absolutely obsolete. Not sure what am I missing here.

**Comment by kuzn123** [comment]
Imagus Mod has one, let's say, "feature" - immediately after installation, saving is prohibited in it. This is what its author decided, although this may cause misunderstanding among some inattentive or inexperienced users. You need to give permission to save by checking the appropriate box in the Settings on the Shortcuts tab. And you should not forget to do this every time after reinstalling the extension. It is also important not to forget to click SAVE after each change of Settings or import of sieves.

Everything works perfectly fine for all users, Imgur is a very large hosting service, but no one complains. Therefore, the problem is only on your computer (some settings are lost or not set, a conflict with another extension, problems with the browser itself, and so on). In such cases, it is recommended to read carefully, and then consistently and accurately follow the recommendations from [this section](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=9#1).

**Comment by ReEnMikki** [comment]
> Imagus Mod has one, let's say, "feature" - immediately after installation, saving is prohibited in it. This is what its author decided, although this may cause misunderstanding among some inattentive or inexperienced users. You need to give permission to save by checking the appropriate box in the Settings on the Shortcuts tab.
![bu3xzbyyz9581](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/114931925/4909a6e5-c6d7-4546-90ca-45562fbea09f)
