### ISSUE TITLE
about changing the update function

### ISSUE THREAD

**Issue by TheFantasticWarrior** [TheFantasticWarrior/chrome-extension-imagus#7]
@kuzn123 
The update sieve (import and auto update) function does "if new sieve doesn't exist but old sieve does, keep the old sieve if it's before dereferers". It seems useful for sieve developing/customizing, as in the original sieve set "dereferers" is on the very top. Or should I just delete everything?
Or should I keep the toggle or add a "pinned" section, or will the Reddit/youtube/other sieves that need customization update to the point that the FAQ will be changed?

**Comment by kuzn123** [comment]
I can't speak for all users, because everyone has the right to create their own set of sieves and update it as they want. The same goes for the author Imagus and his set of rules. But, unfortunately, he no longer supports them.

But in our rule-set (based on sieves from the Ru-Board forum), the order of updating is adopted by **completely removing** all sieves. At the same time, you need to make sure that they are deleted - to do this, you must delete it, click SAVE, exit the Settings, go back to them, make sure that the SIEVES tab is empty - and only then import new sieves.

Also, especially for those who make their own rule-sets, in our update (with a ZIP file) there is a directory "Separately").

**Comment by TheFantasticWarrior** [comment]
So that means I just change it to delete everything and sieve creators have their own solution?
I can modify the code to wipe the sieve AND save automatically, and you actually only need to press save, if you really want to make sure just reload does the same thing

**Comment by kuzn123** [comment]
> I can modify the code to wipe the sieve AND save automatically, and you actually only need to press save, if you really want to make sure just reload does the same thing

I don't mind at all if there are such improvements in your mod.

**Comment by TheFantasticWarrior** [comment]
changed in https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/tag/v0.10.8
